version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - old_pgdata:/var/lib/postgresql/data
    networks:
      - spring_net

  spring1:
    build: .
    container_name: spring1
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      INSTANCE_NAME: spring1
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tienda
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - spring_net

  spring2:
    build: .
    container_name: spring2
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      INSTANCE_NAME: spring2
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tienda
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - spring_net

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring1
      - spring2
    networks:
      - spring_net

volumes:
  old_pgdata:
    external: true
    name: 663322b421c595c81ba4bce8d141b1608d1c6a36335b55bd68f689373f814b6b

networks:
  spring_net:


